strategy: bb1-core-v3p3N2g
data:
  ohlc_4h_csv: data/ohlc/_rescued/4h/BTC-USD.csv
  ohlc_d1_csv: data/ohlc/_rescued/1d/BTC-USD.csv
  ts_col: timestamp
  tz_input: UTC
backtest: { seed_btc: 1.0, reports_dir: reports/mini_accum }
costs: { fee_bps_per_side: 5, slip_bps_per_side: 2, spread_bps_per_side: 0, borrow_bps_annual: 0, funding_bps_daily: 0 }
signals:
  ema_fast: 13
  ema_slow: 55
  cross_buffer_bps: 36
  exit_active: { enabled: false }   # como H1_FZ (para aislar cruce puro)
anti_whipsaw:
  dwell_bars_min_between_flips: 76
  pause_after_flip_bars: 0
  pause_affects_sell: false
modules:
  atr_regime:
    enabled: true
    percentile_p: 35
    yellow_band_pct: 0.0
    pause_affects_sell: false