strategy: bb1-core-v3p3N2g

data:
  ohlc_4h_csv: data/ohlc/_rescued/4h/BTC-USD.csv
  ohlc_d1_csv: data/ohlc/_rescued/1d/BTC-USD.csv
  ts_col: timestamp
  tz_input: UTC

backtest:
  seed_btc: 1.0
  reports_dir: reports/mini_accum

costs:
  fee_bps_per_side: 5
  slip_bps_per_side: 2
  spread_bps_per_side: 0
  borrow_bps_annual: 0
  funding_bps_daily: 0

signals:
  ema_fast: 13
  ema_slow: 55
  cross_buffer_bps: 48         # subir buffer para filtrar cruces marginales
  exit_active:
    enabled: true
    confirm_bars: 1
    max_wait_bars_after_confirm: 2
    age_valve_enabled: false   # NO forzar venta por edad; evita “saca-mete”

anti_whipsaw:
  dwell_bars_min_between_flips: 36   # ↑ dwell para cortar ping-pong
  pause_after_flip_bars: 8           # pequeña pausa tras flip
  pause_affects_sell: true           # la pausa también bloquea ventas

flip_budget:
  enforce_hard_yearly: true
  hard_per_year: 26
  soft_per_week: 1                   # throttle semanal de BUY

modules:
  atr_regime:
    enabled: true
    percentile_p: 35
    yellow_band_pct: 0.08            # banda amarilla un poco más ancha
    pause_affects_sell: true         # en amarillo: ni compra ni vende