[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mini-accum"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "pandas>=2.0",
  "numpy>=1.24",
  "pyyaml>=6.0"
]
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Rafael Cifuentes"}]

[project.scripts]
mini-accum-backtest = "mini_accum.cli:main"
mini-accum-dictamen = "mini_accum.dictamen:main"

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q"

[tool.ruff]
line-length = 100
