version: 0.1
numeraire: BTC
asset: BTC-USD
timezone: UTC

data:
  ohlc_4h_csv: data/ohlc/_rescued/4h/BTC-USD.csv
  ohlc_d1_csv: data/ohlc/_rescued/1d/BTC-USD.csv
  ts_col: timestamp
  price_col: close
  tz_input: UTC

signals:
  ema_fast: __EMA_FAST__
  ema_slow: 55
  cross_buffer_bps: __XB__
  macro_buffer_bps: __MB__
  entry: ema__EMA_FAST__ > ema55 and macro_green
  exit_active:
    rule: close < ema__EMA_FAST__
    confirm_bars: __CONFIRM__
  exit_passive:
    rule: ema__EMA_FAST__ < ema55

anti_whipsaw:
  dwell_bars_4h: __DW__
  dwell_bars_min_between_flips: __DW__
  grace_ttl_bars_4h: __TTL__
  ttl_confirm_bars: __TTL_CONFIRM__

costs:
  fee_bps_per_side: 6.0
  slip_bps_per_side: 6.0

backtest:
  reports_dir: reports/mini_accum
  seed_btc: 1.0

kpis:
  accept:
    net_btc_ratio_min: 1.05
    mdd_vs_hodl_ratio_max: 0.85
    flips_per_year_max: 26
    flips_per_month_soft: 2

flip_budget:
  enforce_hard_yearly: true
  hard_per_year: 26
  allow_riskoff_over_budget: true

modules:
  weekly_turnover_budget:
    enabled: true
    flips_per_week_max: 1
    dynamic_by_atr: true
    enforce_hard: false
  atr_regime:
    enabled: true
    lookback_bars: 14
    percentile_p: 35
    yellow_band_pct: 5
    pause_affects_sell: true
  macro_persist:
    enabled: false

force_sell_on_macro_red: false
