rebalance_freq: 4h
timezone: UTC
costs:
  fee_bps: 6
  slip_bps: 6

exec:
  round_step: 0.20          # si hoy está en 0.10/0.15, súbelo a 0.20
  max_delta_weight_bar: 0.10  # de 0.20 → 0.10 para repartir los cambios

alloc_base:
  diamante: 0.0   # antes 0.50
  perla:    1.00   # antes 0.50

risk:
  vol_target_ann: 0.12
  w_cap_total:    1.20
  vol_clamp:
    min: 0.50
    max: 5.00
  vol_estimator:
    ewm_span: 60
    vol_floor_ann: 0.10       # (opcional) piso de vol para evitar scale enormes
throttle:
  enabled: true
  span_bars: 60               # menos nervioso que 36
  factor_when_neg: 0.65

corr_gate:
  enabled: true
  lookback_bars: 72     # ~12 días (4h)
  threshold: 0.35
  max_penalty: 0.30
  perf_window_days: 30


xi_star:
  cap: 1.65
# configs/allocator_sombra.yaml
files:
  diamante: signals/diamante.csv
  perla:    signals/perla.csv        # <- en vez de reports/allocator/perla_for_allocator.csv
  heart_weights: corazon/weights.csv
  heart_lq: corazon/lq.csv
  xi_star: reports/heart/xi_star.txt
outputs:
  kpis: reports/allocator/sombra_kpis.md
  equity_dir: reports/allocator/curvas_equity/
  weights_overlay: reports/allocator/weights_overlay.csv


