as_of: 2025-08-05 00:00
status: "en evaluación W3–W4 (no blindado)"
notes: >
  BTC candidato: T=0.60 + SL=1.25 + TP1=0.70 + P=0.80. Base pasa gate,
  pero falla stress de fricción en los 2 freezes más recientes
  (PF_ratio<0.90 y MDD_ratio>1.20). Mantener forward-chaining y
  testear vecinos (TP1=0.65 con SL=1.25; y T=0.58 con el mismo SL/TP/P).

# configs/diamante_selected.yaml (limpio)
as_of: 2025-08-05 00:00
notes: "BTC: vecino robusto tras stress; ETH t=0.61; SOL en observación."
diamante:
  BTC-USD:
    threshold: 0.60          # (principal)
    horizons: [30, 60, 90]
    sl_atr_mul: 1.25
    tp1_atr_mul: 0.65
    partial_pct: 0.80
    slip: 0.0002
    cost: 0.0004
  ETH-USD:
    threshold: 0.61
    horizons: [60]
  SOL-USD:
    status: watch

notes: >
  W5: Vecino B (T=0.58 SL=1.25 TP1=0.70 P=0.80) elegido como candidato por PF_base>=1.5,
  con PF_ratio_med~0.904 (sensibilidad moderada a fricción).
  Vecino A (T=0.60 SL=1.25 TP1=0.65 P=0.80) queda como fallback más robusto (PF_ratio_med~0.988).
  Cadencia: semanal. Continuar forward-chaining y registrar pass_both por freeze.
