version: 0.1
numeraire: BTC
asset: BTC-USD
timezone: UTC
data:
  ohlc_4h_csv: data/ohlc/_rescued/4h/BTC-USD.csv
  ohlc_d1_csv: data/ohlc/_rescued/1d/BTC-USD.csv
  ts_col: timestamp
  price_col: close
  tz_input: UTC
signals:
  ema_fast: 21
  ema_slow: 55
  entry: ema21 > ema55 and macro_green
  exit_active:
    rule: close < ema21 and next_close <= next_ema21
    confirm_bars: 1
  exit_passive:
    rule: ema21 < ema55
anti_whipsaw:
  dwell_bars_min_between_flips: 4
  ttl_confirm_bars: 1
costs:
  fee_bps_per_side: 6
  slip_bps_per_side: 6
flip_budget:
  enforce_hard_yearly: true
  hard_per_year: 26
  soft_per_month: 2
backtest:
  reports_dir: reports/mini_accum
  seed_btc: 1.0
kpis:
  accept:
    net_btc_ratio_min: 1.05
    mdd_vs_hodl_ratio_max: 0.85
    flips_per_year_max: 26
    flips_per_month_soft: 2
modules:
  hibernation_chop:
    enabled: false
    window_bars: 40
    min_crosses: 2
    pause_mode: entries_only
  grace_ttl:
    enabled: false
    bars_after_flip: 1
    ema_spread_bps: 30
  weekly_turnover_budget:
    enabled: true
    max_flips_per_week: 2
  atr_regime:
    enabled: false
    lookback_bars: 14
    percentile_p: 40
    yellow_band_pct: 3
  macro_persist:
    enabled: false
    bars: 12
