version: 0.1
numeraire: BTC
asset: BTC-USD
timezone: UTC
data:
  ohlc_4h_csv: data/ohlc/_rescued/4h/BTC-USD.csv
  ohlc_d1_csv: data/ohlc/_rescued/1d/BTC-USD.csv
  ts_col: timestamp
  price_col: close
  tz_input: UTC
signals:
  ema_fast: 21
  ema_slow: 55
  cross_buffer_bps: 15  # exige ema21 > ema55*(1+0.0015); evita microcruces
  entry: ema21 > ema55 and macro_green
  exit_active:
    rule: close < ema21 and next_close <= next_ema21
    confirm_bars: 1
  exit_passive:
    rule: ema21 < ema55
anti_whipsaw:
  dwell_bars_min_between_flips: 6
  ttl_confirm_bars: 1
costs:
  fee_bps: 6
  slip_bps: 6
  fee_bps_per_side: 6.0
  slip_bps_per_side: 6.0
backtest:
  reports_dir: reports/mini_accum
  seed_btc: 1.0
kpis:
  accept:
    net_btc_ratio_min: 1.05
    mdd_vs_hodl_ratio_max: 0.85
    flips_per_year_max: 26
    flips_per_month_soft: 2
modules:
  hibernation_chop:
    enabled: false
  grace_ttl:
    enabled: false
  weekly_turnover_budget:
    enabled: true
    flips_per_week_max: 1
    dynamic_by_atr: true
  atr_regime:
    enabled: true
    lookback_bars: 14
    percentile_p: 40
    yellow_band_pct: 3
  macro_persist:
    enabled: false
  force_sell_on_macro_red: false